/* GENERATED by tools/prepare-audio.mjs — do not edit by hand.
   Self-hosted trimmed/normalized anthem files (served from /audio/, files
   themselves are gitignored — regenerate before deploy). Offsets are baked
   into these files, so their startOffset is always 0. */
export const LOCAL_AUDIO: Record<string, { file: string; duration: number }> = {
  "Mexico": {
    "file": "mx.mp3",
    "duration": 101.8
  },
  "South Africa": {
    "file": "za.mp3",
    "duration": 122.7
  },
  "South Korea": {
    "file": "kr.mp3",
    "duration": 57.4
  },
  "Czechia": {
    "file": "cz.mp3",
    "duration": 64.7
  },
  "Canada": {
    "file": "ca.mp3",
    "duration": 79
  },
  "Bosnia and Herzegovina": {
    "file": "ba.mp3",
    "duration": 124.6
  },
  "Qatar": {
    "file": "qa.mp3",
    "duration": 86.6
  },
  "Switzerland": {
    "file": "ch.mp3",
    "duration": 84.3
  },
  "Brazil": {
    "file": "br.mp3",
    "duration": 112.8
  },
  "Morocco": {
    "file": "ma.mp3",
    "duration": 67.3
  },
  "Haiti": {
    "file": "ht.mp3",
    "duration": 36.9
  },
  "United States": {
    "file": "us.mp3",
    "duration": 78.3
  },
  "Paraguay": {
    "file": "py.mp3",
    "duration": 195.3
  },
  "Australia": {
    "file": "au.mp3",
    "duration": 54.4
  },
  "Türkiye": {
    "file": "tr.mp3",
    "duration": 83.3
  },
  "Germany": {
    "file": "de.mp3",
    "duration": 74.1
  },
  "Ivory Coast": {
    "file": "ci.mp3",
    "duration": 67.5
  },
  "Ecuador": {
    "file": "ec.mp3",
    "duration": 198.9
  },
  "Netherlands": {
    "file": "nl.mp3",
    "duration": 48.3
  },
  "Japan": {
    "file": "jp.mp3",
    "duration": 58.7
  },
  "Sweden": {
    "file": "se.mp3",
    "duration": 87.6
  },
  "Tunisia": {
    "file": "tn.mp3",
    "duration": 51.9
  },
  "Belgium": {
    "file": "be.mp3",
    "duration": 62.2
  },
  "Egypt": {
    "file": "eg.mp3",
    "duration": 85.8
  },
  "Iran": {
    "file": "ir.mp3",
    "duration": 50.4
  },
  "New Zealand": {
    "file": "nz.mp3",
    "duration": 62.9
  },
  "Spain": {
    "file": "es.mp3",
    "duration": 61.9
  },
  "Cape Verde": {
    "file": "cv.mp3",
    "duration": 70.5
  },
  "Saudi Arabia": {
    "file": "sa.mp3",
    "duration": 50
  },
  "Uruguay": {
    "file": "uy.mp3",
    "duration": 55.9
  },
  "France": {
    "file": "fr.mp3",
    "duration": 79.3
  },
  "Senegal": {
    "file": "sn.mp3",
    "duration": 55.8
  },
  "Iraq": {
    "file": "iq.mp3",
    "duration": 105.4
  },
  "Norway": {
    "file": "no.mp3",
    "duration": 62.3
  },
  "Argentina": {
    "file": "ar.mp3",
    "duration": 66
  },
  "Algeria": {
    "file": "dz.mp3",
    "duration": 77.7
  },
  "Austria": {
    "file": "at.mp3",
    "duration": 89.5
  },
  "Jordan": {
    "file": "jo.mp3",
    "duration": 36.4
  },
  "Portugal": {
    "file": "pt.mp3",
    "duration": 69.6
  },
  "DR Congo": {
    "file": "cd.mp3",
    "duration": 87.1
  },
  "Uzbekistan": {
    "file": "uz.mp3",
    "duration": 146.2
  },
  "Colombia": {
    "file": "co.mp3",
    "duration": 160.9
  },
  "England": {
    "file": "gb-eng.mp3",
    "duration": 60.8
  },
  "Croatia": {
    "file": "hr.mp3",
    "duration": 59.4
  },
  "Ghana": {
    "file": "gh.mp3",
    "duration": 57.1
  },
  "Panama": {
    "file": "pa.mp3",
    "duration": 109.8
  }
}
