/* Spanish + French names for the 48 qualified nations. Accepted as guesses
   regardless of UI language (a Spanish speaker types "Alemania" even with the
   UI in English). `alt` carries long/official variants worth accepting.
   Names identical to English (Canada, France, Panama…) are listed anyway so
   this table is a complete review surface — matching de-dupes for free. */

export const NATION_NAMES_I18N: Record<string, { es: string; fr: string; alt?: string[] }> = {
  Mexico: { es: 'México', fr: 'Mexique' },
  'South Africa': { es: 'Sudáfrica', fr: 'Afrique du Sud' },
  'South Korea': { es: 'Corea del Sur', fr: 'Corée du Sud' },
  Czechia: {
    es: 'Chequia',
    fr: 'Tchéquie',
    alt: ['república checa', 'république tchèque'],
  },
  Canada: { es: 'Canadá', fr: 'Canada' },
  'Bosnia and Herzegovina': { es: 'Bosnia y Herzegovina', fr: 'Bosnie-Herzégovine' },
  Qatar: { es: 'Catar', fr: 'Qatar' },
  Switzerland: { es: 'Suiza', fr: 'Suisse' },
  Brazil: { es: 'Brasil', fr: 'Brésil' },
  Morocco: { es: 'Marruecos', fr: 'Maroc' },
  Haiti: { es: 'Haití', fr: 'Haïti' },
  Scotland: { es: 'Escocia', fr: 'Écosse' },
  'United States': { es: 'Estados Unidos', fr: 'États-Unis', alt: ['etats unis'] },
  Paraguay: { es: 'Paraguay', fr: 'Paraguay' },
  Australia: { es: 'Australia', fr: 'Australie' },
  Türkiye: { es: 'Turquía', fr: 'Turquie' },
  Germany: { es: 'Alemania', fr: 'Allemagne' },
  Curaçao: { es: 'Curazao', fr: 'Curaçao' },
  'Ivory Coast': { es: 'Costa de Marfil', fr: 'Côte d’Ivoire', alt: ["cote d'ivoire"] },
  Ecuador: { es: 'Ecuador', fr: 'Équateur' },
  Netherlands: { es: 'Países Bajos', fr: 'Pays-Bas', alt: ['holanda', 'hollande'] },
  Japan: { es: 'Japón', fr: 'Japon' },
  Sweden: { es: 'Suecia', fr: 'Suède' },
  Tunisia: { es: 'Túnez', fr: 'Tunisie' },
  Belgium: { es: 'Bélgica', fr: 'Belgique' },
  Egypt: { es: 'Egipto', fr: 'Égypte' },
  Iran: { es: 'Irán', fr: 'Iran' },
  'New Zealand': { es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande' },
  Spain: { es: 'España', fr: 'Espagne' },
  'Cape Verde': { es: 'Cabo Verde', fr: 'Cap-Vert' },
  'Saudi Arabia': { es: 'Arabia Saudita', fr: 'Arabie saoudite', alt: ['arabia saudí'] },
  Uruguay: { es: 'Uruguay', fr: 'Uruguay' },
  France: { es: 'Francia', fr: 'France' },
  Senegal: { es: 'Senegal', fr: 'Sénégal' },
  Iraq: { es: 'Irak', fr: 'Irak' },
  Norway: { es: 'Noruega', fr: 'Norvège' },
  Argentina: { es: 'Argentina', fr: 'Argentine' },
  Algeria: { es: 'Argelia', fr: 'Algérie' },
  Austria: { es: 'Austria', fr: 'Autriche' },
  Jordan: { es: 'Jordania', fr: 'Jordanie' },
  Portugal: { es: 'Portugal', fr: 'Portugal' },
  'DR Congo': {
    es: 'RD del Congo',
    fr: 'RD Congo',
    alt: ['república democrática del congo', 'république démocratique du congo'],
  },
  Uzbekistan: { es: 'Uzbekistán', fr: 'Ouzbékistan' },
  Colombia: { es: 'Colombia', fr: 'Colombie' },
  England: { es: 'Inglaterra', fr: 'Angleterre' },
  Croatia: { es: 'Croacia', fr: 'Croatie' },
  Ghana: { es: 'Ghana', fr: 'Ghana' },
  Panama: { es: 'Panamá', fr: 'Panama' },
}
