/* GENERATED by tools/measure-offsets.mjs — do not edit by hand.
   Leading-silence offsets (seconds) per anthem recording: the clip window
   starts here so a 1s first clip is always audible. Reveal playback still
   starts at 0 (the intro is part of the anthem). */
export const START_OFFSETS: Record<string, number> = {
  "Bosnia and Herzegovina": 0.5,
  "Qatar": 2,
  "Morocco": 0.5,
  "Paraguay": 0.6,
  "Türkiye": 0.6,
  "Ivory Coast": 1.7,
  "Netherlands": 0.4,
  "Tunisia": 0.5,
  "Belgium": 0.9,
  "Spain": 0.5,
  "Cape Verde": 0.7,
  "Saudi Arabia": 0.9,
  "Algeria": 0.5,
  "Jordan": 2.5,
  "Portugal": 0.5,
  "DR Congo": 2,
  "England": 2.3,
  "Ghana": 0.5
}
