#!/usr/bin/env node
/* Measure leading silence in every anthem recording and emit
   src/lib/anthem/offsets.ts — per-anthem clip start offsets so the 1-second
   first clip is never a silent intro (HANDOFF §5 known limitation).
   Downloads are cached in /tmp/anthem-audio. Requires ffmpeg.
   Usage: node tools/measure-offsets.mjs */
import { execSync, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const CACHE = '/tmp/anthem-audio'
mkdirSync(CACHE, { recursive: true })

/* pull names + audio paths straight from the data module */
const puzzlesSrc = readFileSync(join(here, '../src/lib/anthem/puzzles.ts'), 'utf-8')
const entries = [
  ...puzzlesSrc.matchAll(/name:"([^"]+)"[\s\S]*?audio:(null|"([^"]+)")/g),
].map((m) => ({ name: m[1], audio: m[3] || null }))
const withAudio = entries.filter((e) => e.audio)
console.log(`${withAudio.length} anthems with audio`)

const BASE = 'https://archive.org/download/us-navy-band-national-anthems-public-domain/'

function leadingSilence(file) {
  /* silencedetect: report stretches quieter than -32dB lasting >=0.25s; if the
     track opens with one, its silence_end is our offset. ffmpeg writes the
     filter log to STDERR, so capture that. */
  const r = spawnSync(
    'ffmpeg',
    ['-hide_banner', '-i', file, '-af', 'silencedetect=noise=-32dB:d=0.25', '-t', '20', '-f', 'null', '-'],
    { encoding: 'utf-8' },
  )
  return (r.stderr || '') + (r.stdout || '')
}

/* Human listening verdicts (docs/research/qa-listen.md): these intros are
   soft (-37..-27dB) rather than silent, so silencedetect@-32dB misses them.
   Floor, not replacement — a louder future measurement still wins. */
const EAR_FLOOR = { Qatar: 2, Jordan: 2.5 }

const offsets = {}
for (const { name, audio } of withAudio) {
  const cached = join(CACHE, audio.replace(/[\/ ]/g, '_'))
  if (!existsSync(cached) || statSync(cached).size < 10000) {
    const url = BASE + encodeURI(audio)
    try {
      execSync(`curl -sL --max-time 120 -o "${cached}" "${url}"`)
    } catch {
      console.error(`download failed: ${name}`)
      continue
    }
  }
  const log = leadingSilence(cached)
  const start = log.match(/silence_start: (-?[\d.]+)/)
  const end = log.match(/silence_end: ([\d.]+)/)
  let off = 0
  if (start && end && parseFloat(start[1]) <= 0.1) off = parseFloat(end[1])
  /* only meaningful intros; cap so a detection glitch can't skip half a clip-stage budget */
  off = Math.min(12, Math.round(off * 10) / 10)
  if (EAR_FLOOR[name]) off = Math.max(off, EAR_FLOOR[name])
  if (off >= 0.4) offsets[name] = off
  console.log(`${name.padEnd(24)} ${off >= 0.4 ? off + 's' : '—'}`)
}

const body =
  `/* GENERATED by tools/measure-offsets.mjs — do not edit by hand.\n` +
  `   Leading-silence offsets (seconds) per anthem recording: the clip window\n` +
  `   starts here so a 1s first clip is always audible. Reveal playback still\n` +
  `   starts at 0 (the intro is part of the anthem). */\n` +
  `export const START_OFFSETS: Record<string, number> = ` +
  JSON.stringify(offsets, null, 2) +
  '\n'
writeFileSync(join(here, '../src/lib/anthem/offsets.ts'), body)
console.log(`\nwrote offsets.ts with ${Object.keys(offsets).length} entries`)
