#!/usr/bin/env node
/* Produce self-hosted anthem audio: trim the measured leading silence,
   loudness-normalize, re-encode, and emit both the files (public/audio/,
   gitignored — regenerate before deploy) and a committed manifest module
   (src/lib/anthem/audio-local.ts). The app tries these first and falls back
   to archive.org streaming, then synth — so a checkout without the files
   still works. Requires ffmpeg/ffprobe; downloads cache in /tmp/anthem-audio.
   Usage: node tools/prepare-audio.mjs */
import { createHash } from 'node:crypto'
import { execFileSync, execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const CACHE = '/tmp/anthem-audio'
const OUT = join(here, '../public/audio')
mkdirSync(CACHE, { recursive: true })
mkdirSync(OUT, { recursive: true })

const puzzlesSrc = readFileSync(join(here, '../src/lib/anthem/puzzles.ts'), 'utf-8')
const entries = [
  ...puzzlesSrc.matchAll(/name:"([^"]+)", flag:"[^"]*", cc:"([^"]+)"[\s\S]*?audio:(null|"([^"]+)")/g),
].map((m) => ({ name: m[1], cc: m[2], audio: m[4] || null }))
const withAudio = entries.filter((e) => e.audio)

const offsetsSrc = readFileSync(join(here, '../src/lib/anthem/offsets.ts'), 'utf-8')
const offsets = JSON.parse(offsetsSrc.slice(offsetsSrc.indexOf('{'), offsetsSrc.lastIndexOf('}') + 1))

const BASE = 'https://archive.org/download/us-navy-band-national-anthems-public-domain/'

/* skip the whole encode when nothing that affects output has changed —
   re-encoding 46 files cost ~2 min on every deploy */
const signature = createHash('sha256')
  .update(readFileSync(fileURLToPath(import.meta.url)))
  .update(offsetsSrc)
  .update(JSON.stringify(withAudio))
  .digest('hex')
const sigFile = join(OUT, '.signature')
const allPresent = withAudio.every(({ cc }) => existsSync(join(OUT, `${cc}.mp3`)))
if (allPresent && existsSync(sigFile) && readFileSync(sigFile, 'utf-8') === signature) {
  console.log(`audio up to date (${withAudio.length} files) — skipping encode`)
  process.exit(0)
}

const manifest = {}
let failed = 0

for (const { name, cc, audio } of withAudio) {
  const cached = join(CACHE, audio.replace(/[\/ ]/g, '_'))
  if (!existsSync(cached) || statSync(cached).size < 10000) {
    try {
      execSync(`curl -sL --max-time 120 -o "${cached}" "${BASE}${encodeURI(audio)}"`)
    } catch {
      console.error(`download failed: ${name}`)
      failed++
      continue
    }
  }
  const off = offsets[name] || 0
  const out = join(OUT, `${cc}.mp3`)
  try {
    execFileSync(
      'ffmpeg',
      [
        '-hide_banner', '-loglevel', 'error', '-y',
        ...(off ? ['-ss', String(off)] : []),
        '-i', cached,
        // 30ms fade-in kills the trim click; single-pass loudnorm evens out
        // the wildly different recording levels across the archive
        '-af', 'afade=t=in:d=0.03,loudnorm=I=-16:TP=-1.5:LRA=11',
        '-ar', '44100', '-b:a', '128k', '-map_metadata', '-1',
        out,
      ],
      { stdio: ['pipe', 'pipe', 'inherit'], timeout: 120000 },
    )
    const dur = parseFloat(
      execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', out], {
        encoding: 'utf-8',
      }),
    )
    manifest[name] = { file: `${cc}.mp3`, duration: Math.round(dur * 10) / 10 }
    console.log(`${name.padEnd(24)} ${cc}.mp3  ${manifest[name].duration}s${off ? `  (trimmed ${off}s)` : ''}`)
  } catch (e) {
    console.error(`encode failed: ${name}: ${e.message}`)
    failed++
  }
}

const body =
  `/* GENERATED by tools/prepare-audio.mjs — do not edit by hand.\n` +
  `   Self-hosted trimmed/normalized anthem files (served from /audio/, files\n` +
  `   themselves are gitignored — regenerate before deploy). Offsets are baked\n` +
  `   into these files, so their startOffset is always 0. */\n` +
  `export const LOCAL_AUDIO: Record<string, { file: string; duration: number }> = ` +
  JSON.stringify(manifest, null, 2) +
  '\n'
writeFileSync(join(here, '../src/lib/anthem/audio-local.ts'), body)
console.log(`\n${Object.keys(manifest).length} encoded, ${failed} failed → audio-local.ts`)
if (failed) process.exit(1)
writeFileSync(sigFile, signature)
