/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as AnthemRouteImport } from './routes/anthem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscribeRouteImport } from './routes/api.subscribe'
import { Route as ApiEventRouteImport } from './routes/api.event'
import { Route as ApiAnthemStatsRouteImport } from './routes/api.anthem-stats'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AnthemRoute = AnthemRouteImport.update({
  id: '/anthem',
  path: '/anthem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventRoute = ApiEventRouteImport.update({
  id: '/api/event',
  path: '/api/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthemStatsRoute = ApiAnthemStatsRouteImport.update({
  id: '/api/anthem-stats',
  path: '/api/anthem-stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anthem': typeof AnthemRoute
  '/og': typeof OgRoute
  '/api/anthem-stats': typeof ApiAnthemStatsRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anthem': typeof AnthemRoute
  '/og': typeof OgRoute
  '/api/anthem-stats': typeof ApiAnthemStatsRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anthem': typeof AnthemRoute
  '/og': typeof OgRoute
  '/api/anthem-stats': typeof ApiAnthemStatsRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anthem'
    | '/og'
    | '/api/anthem-stats'
    | '/api/event'
    | '/api/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anthem'
    | '/og'
    | '/api/anthem-stats'
    | '/api/event'
    | '/api/subscribe'
  id:
    | '__root__'
    | '/'
    | '/anthem'
    | '/og'
    | '/api/anthem-stats'
    | '/api/event'
    | '/api/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnthemRoute: typeof AnthemRoute
  OgRoute: typeof OgRoute
  ApiAnthemStatsRoute: typeof ApiAnthemStatsRoute
  ApiEventRoute: typeof ApiEventRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anthem': {
      id: '/anthem'
      path: '/anthem'
      fullPath: '/anthem'
      preLoaderRoute: typeof AnthemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event': {
      id: '/api/event'
      path: '/api/event'
      fullPath: '/api/event'
      preLoaderRoute: typeof ApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthem-stats': {
      id: '/api/anthem-stats'
      path: '/api/anthem-stats'
      fullPath: '/api/anthem-stats'
      preLoaderRoute: typeof ApiAnthemStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnthemRoute: AnthemRoute,
  OgRoute: OgRoute,
  ApiAnthemStatsRoute: ApiAnthemStatsRoute,
  ApiEventRoute: ApiEventRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
